import { ADTClient, session_types, HttpClient } from 'abap-adt-api';
import { executeHttpRequest } from '@sap-cloud-sdk/http-client';
import { getDestination, Destination } from '@sap-cloud-sdk/connectivity';
import { McpError, ErrorCode } from "@modelcontextprotocol/sdk/types.js";

// Custom HttpClient that routes ADT requests through BTP Destination via SAP Cloud SDK
// Includes an automated Cookie Manager to preserve the ABAP Session (SAP_SESSIONID, etc.)
// which is strictly required for stateful lock -> set source -> unlock operations.
class BtpDestinationHttpClient implements HttpClient {
  private cookies: Map<string, string> = new Map();

  constructor(private destination: Destination, private userJwt: string) {}

  private getCookieString(): string {
    return Array.from(this.cookies.entries())
      .map(([k, v]) => `${k}=${v}`)
      .join('; ');
  }

  private updateCookies(setCookieHeaders: string[] | string | undefined) {
    if (!setCookieHeaders) return;
    const headers = Array.isArray(setCookieHeaders) ? setCookieHeaders : [setCookieHeaders];
    for (const header of headers) {
      // Extract "Name=Value" before the first semicolon in the Set-Cookie string
      const match = header.match(/^([^=;\s]+)=([^;]+)/);
      if (match) {
        this.cookies.set(match[1].trim(), match[2].trim());
      }
    }
  }

  async request(options: any): Promise<any> {
    try {
      // options.url is an absolute URL generated by abap-adt-api.
      // We must extract the relative path because executeHttpRequest 
      // expects a relative path to append to the Destination URL and apply CC proxy.
      let relativePath = options.url;
      try {
        const parsedUrl = new URL(options.url);
        relativePath = parsedUrl.pathname + parsedUrl.search;
      } catch (e) {
        // If already relative, ignore
      }

      // Remove dummy headers generated by abap-adt-api's native client
      const cleanedHeaders = { ...options.headers };
      delete cleanedHeaders['host'];
      delete cleanedHeaders['authorization']; // Remove dummy Basic auth to allow Principal Propagation

      // Attach cookies to maintain stateful ABAP sessions
      const sessionCookies = this.getCookieString();
      if (sessionCookies) {
        cleanedHeaders['cookie'] = cleanedHeaders['cookie'] 
          ? `${cleanedHeaders['cookie']}; ${sessionCookies}` 
          : sessionCookies;
      }

      const response = await executeHttpRequest(this.destination as any, {
        method: options.method || 'GET',
        url: relativePath,
        data: options.body,
        headers: cleanedHeaders,
        params: options.qs,
        // SAP Cloud SDK handles proxying, SSL, and PrincipalPropagation via the JWT
      }, {
        fetchCsrfToken: false // ADT client manually manages CSRF
      });

      // Retrieve new stateful cookies (SAP_SESSIONID etc) and remember them
      this.updateCookies(response.headers['set-cookie']);

      return {
        body: typeof response.data === 'string' ? response.data : JSON.stringify(response.data),
        status: response.status,
        statusText: response.statusText,
        headers: response.headers as any,
        request: response.config
      };
    } catch (error: any) {
      const errMsg = error.response ? `${error.response.status}: ${JSON.stringify(error.response.data)}` : error.message;
      throw new Error(`BTP HTTP Request Failed: ${errMsg}`);
    }
  }
}

export async function createBtpAdtClient(userJwt: string, destinationName: string): Promise<ADTClient> {
  try {
    // Retrieve destination using the user's JWT
    const destination = await getDestination({
      destinationName,
      jwt: userJwt,
      useCache: true
    });

    const url = destination?.url;
    if (!url) {
      throw new Error(`Destination '${destinationName}' is missing a valid URL.`);
    }

    // Initialize ADTClient with the URL from destination.
    // We pass dummy username/password to satisfy the constructor's validation,
    // as our customHttpClient will handle the actual authentication via JWT.
    const client = new ADTClient(
      url,
      'BTP_USER',
      'BTP_PASSWORD',
      process.env.SAP_CLIENT || '',
      process.env.SAP_LANGUAGE || 'EN'
    );

    const customHttpClient = new BtpDestinationHttpClient(destination, userJwt);
    
    // The httpClient property on ADTClient is a getter on the prototype.
    // We must use Object.defineProperty to override it on the instance.
    Object.defineProperty(client, 'httpClient', {
      value: customHttpClient,
      writable: true,
      enumerable: true,
      configurable: true
    });

    client.stateful = session_types.stateful;

    return client;
  } catch (err: any) {
    throw new McpError(ErrorCode.InternalError, `Failed to initialize BTP ADT Client: ${err.message}`);
  }
}
